locais=['japão','alemanha','coreia do sul','inglaterra','china']
print(locais, '\n')
print(sorted(locais),'\n')
print(locais, '\n')
print(sorted(locais, reverse=True),'\n')
print(locais, '\n')
locais.reverse()
print(locais, '\n')
locais.reverse()
print(locais, '\n')
locais.sort()
print(locais, '\n')
locais.sort(reverse=True)
print(locais)