idiomas=[]
idiomas.append('português')
idiomas.append('inglês')
idiomas.append('japonês')
idiomas.append('coreano')
print(idiomas)
idiomas[3]= 'chinês'
print(idiomas)
message= 'Meu primeiro idioma foi o ' + idiomas[0].title()
print(message)
print(sorted(idiomas))
print(sorted(idiomas, reverse=True))
print(idiomas)
idiomas.sort()
print(idiomas)
idiomas.sort(reverse=True)
print(idiomas)
idiomas.reverse()
print(idiomas)
idiomas.reverse()
print(idiomas)
idiomas.insert(4, 'coreano')
print(idiomas)
idiomas.append('alemão')
print(idiomas)
remover= 'português'
idiomas.remove(remover)
print(idiomas)
idiomas.pop()
print(idiomas)
del idiomas[0]
print(idiomas)
print(len(idiomas))